<!DOCTYPE html>
<html lang="en">
<head>
<!--head-->
<?php include dirname(__FILE__) ."./../include/head.php"; ?>					
<!--head end-->		
</head>
<body>
    <div class="wrapper">	
<!--sidebar-->
<?php  include dirname(__FILE__) ."./../include/side.php"; ?>					
<!--sidebar end-->		
        <div class="main-panel">	
			<!--nav　インクルード　-->
			<?php  //include dirname(__FILE__) ."./../include/nav.php"; ?>
			<!--nav　インクルード　end-->
			           <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card strpied-tabled-with-hover">
                                <div class="card-header ">
                                    <h4 class="card-title">movie_info dbのmovie_infoテーブルからデータ取得</h4>
                                    <p class="card-category">src/setting.phpにデータベース情報記載</p>
									<p class="card-category">src/dependencies.phpにdsn情報記載</p>
                                </div>
                                <div class="card-body table-full-width table-responsive">
                                   <table class="table table-hover table-striped">
									<thead>
										<th>num : uuid</th>
										<th>block</th>
										<th>削除</th>			
									</thead>
									<tbody>
									<?php $id = $_GET[id]; echo "飛んできたID：".$id;?>
									<?php $details = $data->ch2_info_details($id); ?>
									<?php foreach($details as $test): ?>
									<tr>
										<!--(1)-->
										<td style="width:10px"  class="text-center">
										<?=$test['num'] ?>:<?=$test['uuid'] ?>
										</td>
										<!--(2)-->
										<td style="width:100px"  class="text-left">
										<div style="text-align: center">
										<form action ="" method ="post">
											<textarea name="content" rows="3" cols="50" style="vertical-align: middle"><?=$test['block'] ?></textarea>
											<input type="hidden" value="<?=$test['id'] ?>" name="id_up">
											<input type="hidden" value="<?=$test['num'] ?>" name="num_up">
											<input type = "submit" class="btn btn-primary" value ="更新" name="up">
										</form>
										</div>
										</td>
										<!--(3)-->
										<td>
										<form action ="" method ="post">
											<input type="hidden" value="<?=$test['id'] ?>" name="id_del">
											<input type="hidden" value="<?=$test['num'] ?>" name="num_del">
											<input type = "submit" class="btn btn-primary" value ="削除">
										</form>
										</td>
									</tr>
									<?php endforeach; ?>
									</tbody>
								  </table>
						  
                                </div>
                            </div>
                        </div>			
            <footer class="footer">
					<!--copywrite-->
					<?php  include dirname(__FILE__) ."./../include/copywrite.php"; ?>					
					<!--copywrite end-->	
            </footer>
        </div>
    </div>
</body>
</body>
<!--core_js-->
<?php  include dirname(__FILE__) ."./../include/core_js.php"; ?>					
<!--core_js end-->		
</html>

<?php
//削除、更新の関数の実行  現在のページのURLを取得
$url = (empty($_SERVER["HTTPS"]) ? "http://" : "https://").$_SERVER["HTTP_HOST"].$_SERVER["REQUEST_URI"];

//update ボタンが押された場合
(int)$id_up = $_POST["id_up"];
(int)$num_up =  $_POST["num_up"];
$block = $_POST["content"];
												
//削除ボタンが押された時　カラムを削除する
(int)$id_del = $_POST["id_del"]; 
(int)$num_del = $_POST["num_del"];

//空白じゃない時を実行しないと、タイトルページから詳細ページに移行する時エラー起こる
//なぜなら初期がnullの為である。その為エラーが起きる。
if(!empty($id_del) && !empty($num_del)){
	$details = $data->ch2_delete($id_del,$num_del);
	//削除関数実行と共に、更新を行う
	header('Location:'.$url.'');
	exit();
//更新ボタンが押された時、関数実行
}else if($_POST["up"]){	
	$details = $data->ch2_update($id_up,$num_up,$block);
	
	//削除関数実行と共に、更新を行う
	header('Location:'.$url.'');
	exit();
}else{
//何もしないで終了
}
?>