<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>テスト</title>
    </head>
<?php
header('Content-Type: text/html; charset=UTF-8')
?>
	<?php 
	echo "book_api.phtml<br>";
	
	var_dump($data);
	$books = $data->getTests();
	var_dump($books);
	?>
		<table class="pure-table">
		  <tr>
			<th>id</th>
			<th>title</th>
			<th>name</th>
		  </tr>
		<?php foreach($books as $test): ?>
		  <tr>
			<td><?=$test['id'] ?></td>
			<td><?=$test['title'] ?></td>
			<td><?=$test['name'] ?></td>
		  </tr>
		<?php endforeach; ?>
		</table>

</html>