<!DOCTYPE html>
<html lang="en">
<head>
<!--head-->
<?php  include dirname(__FILE__) ."./../include/head.php"; ?>					
<!--head end-->		
</head>
<body>
    <div class="wrapper">	
<!--sidebar-->
<?php  include dirname(__FILE__) ."./../include/side.php"; ?>					
<!--sidebar end-->		
        <div class="main-panel">	
			<!--nav　インクルード　-->
			<?php  include dirname(__FILE__) ."./../include/nav.php"; ?>
			<!--nav　インクルード　end-->
			           <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card strpied-tabled-with-hover">
                                <div class="card-header ">
                                    <h4 class="card-title">test dbのbookテーブルからデータ取得</h4>
                                    <p class="card-category">src/setting.phpにデータベース情報記載</p>
									<p class="card-category">src/dependencies.phpにdsn情報記載</p>
                                </div>
                                <div class="card-body table-full-width table-responsive">
                                    <table class="table table-hover table-striped">
                                        <thead>
                                            <th>ID</th>
                                            <th>title</th>
                                            <th>name</th>
                                        </thead>
										<?php 
										//var_dump($data);echo "←データオブジェクト<br>";
										$books = $data->getTests();
										//var_dump($books);
										?>					
                                        <tbody>
										<?php foreach($books as $test): ?>
										  <tr>
											<td><?=$test['id'] ?></td>
											<td style="width:200px"  class="text-center">
											<a title="アカウント詳細"　rel="tooltip"　class="btn btn-info btn-simple btn-xs" 
											href ="/slim3/sample/public/book_api_sample_detail?id=<?=htmlspecialchars($test['id'],ENT_QUOTES,'UTF-8')?>">
											<?=$test['title'] ?>
											</a></td>
											<td><?=$test['name'] ?></td>
										  </tr>
										<?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>			
            <footer class="footer">
					<!--copywrite-->
					<?php  include dirname(__FILE__) ."./../include/copywrite.php"; ?>					
					<!--copywrite end-->	
            </footer>
        </div>
    </div>
</body>
</body>
<!--core_js-->
<?php  include dirname(__FILE__) ."./../include/core_js.php"; ?>					
<!--core_js end-->		
</html>
