<!DOCTYPE html>
<html lang="en">
<head>
<!--head-->
<?php  include dirname(__FILE__) ."./../include/head.php"; ?>					
<!--head end-->		
</head>
<body>
    <div class="wrapper">	
<!--sidebar-->
<?php  include dirname(__FILE__) ."./../include/side.php"; ?>					
<!--sidebar end-->		
        <div class="main-panel">	
			<!--nav　インクルード　-->
			<?php  //include dirname(__FILE__) ."./../include/nav.php"; ?>
			<!--nav　インクルード　end-->
			           <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card strpied-tabled-with-hover">
                                <div class="card-header ">
                                    <h4 class="card-title">movie_info dbのmovie_infoテーブルからデータ取得</h4>
                                    <p class="card-category">src/setting.phpにデータベース情報記載</p>
									<p class="card-category">src/dependencies.phpにdsn情報記載</p>
                                </div>
                                <div class="card-body table-full-width table-responsive">
                                    <table class="table table-hover table-striped">
                                        <thead>
                                            <th>ID</th>
                                            <th>title</th>
											<th>削除</th>
											<th>リスト</th>
											
											
                                        </thead>
										<?php 
										//var_dump($data);echo "←データオブジェクト<br>";
										$title = $data->ch_info();
										//var_dump($books);
										?>					
                                        <tbody>
										<?php foreach($title as $test): ?>
										  <tr>
											<td><?=$test['id'] ?></td>
											
											<td style="width:100%"  class="text-center">
											<a title="アカウント詳細"　rel="tooltip"　class="btn btn-info btn-simple btn-xs" 
											href ="/marble_boot/admin/slim-skeleton/public/
											ch2_info_detail?id=<?=htmlspecialchars($test['id'],ENT_QUOTES,'UTF-8')?>">
											<?=$test['title'] ?>
											</a></td>
											
											<td>
											<form action ="" method ="post">
											<input type="hidden" value="<?=$test['id'] ?>" name="id_del">
											<input type = "submit" class="btn btn-primary" value ="削除" name="del">
											</form>
											</td>
											
											<td>
											<div style="text-align: center">
											<form action ="" method ="post">
											<input type="text" value="<?=$test['list'] ?>" name="id_list">
											<input type="hidden" value="<?=$test['id'] ?>" name="id_up">
											<input type = "submit" class="btn btn-primary" value ="更新" name="list">
											</form>
											</div>
											</td>
										  
										  </tr>
										<?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>			
            <footer class="footer">
					<!--copywrite-->
					<?php  include dirname(__FILE__) ."./../include/copywrite.php"; ?>					
					<!--copywrite end-->	
            </footer>
        </div>
    </div>
</body>
</body>
<!--core_js-->
<?php  include dirname(__FILE__) ."./../include/core_js.php"; ?>					
<!--core_js end-->		
</html>
<?php
//現在のページのURLを取得
$url = (empty($_SERVER["HTTPS"]) ? "http://" : "https://").$_SERVER["HTTP_HOST"].$_SERVER["REQUEST_URI"];?>
<?php
(int)$id_del = $_POST["id_del"]; 
//var_dump($id_del);
//var_dump($_POST["del"]);

//削除ボタンが押された時　カラムを削除する
if(!empty($_POST["del"])){	
	$title_del_details = $data->ch_del($id_del);
	var_dump($title_del_details);	
	header('Location:'.$url.'');
}else{
	//何もしないで終了
	//echo "else";
}


if(!empty($_POST["del"])){		
	$title_del = $data->ch_del_title($id_del);
	var_dump($title_del);
	//削除関数実行と共に、更新を行う
	header('Location:'.$url.'');
	exit();
}else{
	//何もしないで終了
	//echo "else";
}
?>

<?php
//list updata
$list_data = $_POST["id_list"];
$list_id = $_POST["id_up"];
$list_btn = $_POST["list"];
if(!empty($list_btn)){
	$list_up = $data->ch_up_list($list_id,$list_data);
	header('Location:'.$url.'');
	exit();	
}else{
}	
?>