<!DOCTYPE html>
<html lang="en">
<head>
<!--head-->
<?php  include dirname(__FILE__) ."./../include/head.php"; ?>					
<!--head end-->		
</head>
<body>
<div class="wrapper">	
<!--sidebar-->
<?php  include dirname(__FILE__) ."./../include/side.php"; ?>					
<!--sidebar end-->		
<div class="main-panel">	
<!--nav　インクルード　-->
<?php  //include dirname(__FILE__) ."./../include/nav.php"; ?>
<!--nav　インクルード　end-->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card strpied-tabled-with-hover">
                    <div class="card-header ">
                        <h4 class="card-title">list</h4>
                        <p class="card-category">src/setting.phpにデータベース情報記載</p>
						<p class="card-category">src/dependencies.phpにdsn情報記載</p>
                    </div>
                    <div class="card-body table-full-width table-responsive">
                        <table class="table table-hover table-striped">
<tbody>
<?php $title = $data->ch_info(); ?>
<?php foreach($title as $value): ?>
<?php 
//空白の時、未分類を代入する。
if(empty($value["list"])){
$value["list"] ="未分類";	
}else{}
?>
	<a title="アカウント詳細"　rel=/"tooltip"　class="btn btn-info btn-simple btn-xs" 
	href ="/marble_boot/admin/slim-skeleton/public/
	list_detail?list=<?=htmlspecialchars($value['list'],ENT_QUOTES,'UTF-8')?>">
	<?=$value['list'] ?>
	</a>
<hr>

<?php endforeach; ?>	
</tbody>
                        </table>
				
                    </div>
                </div>
            </div>
		</div>
    <footer class="footer">
	<!--copywrite-->
	<?php  include dirname(__FILE__) ."./../include/copywrite.php"; ?>					
	<!--copywrite end-->	
    </footer>
    </div>
</div>
</div>
</div>
</body>
<!--core_js-->
<?php  include dirname(__FILE__) ."./../include/core_js.php"; ?>					
<!--core_js end-->		
</html>