<!DOCTYPE html>
<html lang="en">
<head>
<!--head-->
<?php  include dirname(__FILE__) ."./../include/head.php"; ?>					
<!--head end-->		
</head>
<body>
<div class="wrapper">	
<!--sidebar-->
<?php  include dirname(__FILE__) ."./../include/side.php"; ?>					
<!--sidebar end-->		
<div class="main-panel">	
<!--nav　インクルード　-->
<?php  //include dirname(__FILE__) ."./../include/nav.php"; ?>
<!--nav　インクルード　end-->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card strpied-tabled-with-hover">
                    <div class="card-header ">
                        <h3 class="card-title">list</h3>
					    <h4 class="card-title">list名：<?php echo $_GET["list"];?></h4>
					</div>
                    <div class="card-body table-full-width table-responsive">
                        <table class="table table-hover table-striped">
<tbody>
<?php $list = $_GET["list"]; ?>
<?php $list = $data->ch_list_d($list); 
//var_dump($list);
//var_dump(isset($list[0]));
?>
<?php $i=1;?>
<?php foreach($list as $value): ?>
	<?php echo $i++.":"; ?>
	<a title="アカウント詳細"　rel=/"tooltip"　class="btn btn-info btn-simple btn-xs" 
	href ="/marble_boot/admin/slim-skeleton/public/
	ch2_info_detail?id=<?=htmlspecialchars($value['id'],ENT_QUOTES,'UTF-8')?>">
	<?=$value['title'] ?>
	</a>
	<div style="text-align: right">
	<form action ="" method ="post">
		list名：<input type="text" value="<?=$value['list'] ?>" name="id_list">
		<input type="hidden" value="<?=$value['id'] ?>" name="id_up">
		<input type = "submit" class="btn btn-primary" value ="更新" name="list">
	</form>
	</div>
	<hr>
<?php endforeach; ?>	
</tbody>
                        </table>				
                    </div>
                </div>
            </div>
		</div>
    <footer class="footer">
	<!--copywrite-->
	<?php  include dirname(__FILE__) ."./../include/copywrite.php"; ?>					
	<!--copywrite end-->	
    </footer>
    </div>
</div>
</div>
</div>
</body>
<!--core_js-->
<?php  include dirname(__FILE__) ."./../include/core_js.php"; ?>					
<!--core_js end-->		
</html>

<?php
//list updata
$url = (empty($_SERVER["HTTPS"]) ? "http://" : "https://").$_SERVER["HTTP_HOST"].$_SERVER["REQUEST_URI"];
$list_data = $_POST["id_list"];
$list_id = $_POST["id_up"];
$list_btn = $_POST["list"];
var_dump($list_data);
var_dump($list_id);
var_dump($list_btn);
if(!empty($list_btn)){
	$list_up = $data->ch_up_list($list_id,$list_data);
	if(isset($list[0])===false){
		$url_back = "http://192.168.179.6/marble_boot/admin/slim-skeleton/public/ch2_list";
		//header('Location:'.$url_back.'');
		//exit();
		echo "------";
	}else{
		header('Location:'.$url.'');
		exit();	
	}
}else{}	
?>